# Generated by Django 6.0.6 on 2026-06-11 06:02

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, unique=True)),
                ('installation_id', models.CharField(max_length=100, unique=True)),
                ('encrypted_access_token', dashboard.models.EncryptedField(max_length=512)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, max_length=255)),
                ('repository_name', models.CharField(max_length=255)),
                ('target_language', models.CharField(max_length=50)),
                ('execution_status', models.CharField(max_length=50)),
                ('execution_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
